2022-09-12 22:40:31,873 INFO    StreamThr :92475 [internal.py:wandb_internal():88] W&B internal server running at pid: 92475, started at: 2022-09-12 22:40:31.872392
2022-09-12 22:40:31,875 DEBUG   HandlerThread:92475 [handler.py:handle_request():138] handle_request: status
2022-09-12 22:40:31,876 DEBUG   SenderThread:92475 [sender.py:send_request():315] send_request: status
2022-09-12 22:40:31,878 DEBUG   SenderThread:92475 [sender.py:send():301] send: header
2022-09-12 22:40:31,878 INFO    WriterThread:92475 [datastore.py:open_for_write():75] open: /home/fquesada/Documents/LiteFlowNet_roya/wandb/run-20220912_224031-9/run-9.wandb
2022-09-12 22:40:31,913 DEBUG   SenderThread:92475 [sender.py:send():301] send: run
2022-09-12 22:40:31,915 INFO    SenderThread:92475 [sender.py:_maybe_setup_resume():577] checking resume status for None/roya/9
2022-09-12 22:40:32,604 ERROR   SenderThread:92475 [internal_api.py:execute():202] 409 response executing GraphQL.
2022-09-12 22:40:32,604 ERROR   SenderThread:92475 [internal_api.py:execute():203] {"errors":[{"message":"run franceqa/roya/9 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2022-09-12 22:40:33,964 ERROR   SenderThread:92475 [internal_api.py:execute():202] 409 response executing GraphQL.
2022-09-12 22:40:33,965 ERROR   SenderThread:92475 [internal_api.py:execute():203] {"errors":[{"message":"run franceqa/roya/9 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2022-09-12 22:40:36,408 ERROR   SenderThread:92475 [internal_api.py:execute():202] 409 response executing GraphQL.
2022-09-12 22:40:36,408 ERROR   SenderThread:92475 [internal_api.py:execute():203] {"errors":[{"message":"run franceqa/roya/9 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2022-09-12 22:40:36,409 ERROR   SenderThread:92475 [retry.py:__call__():154] Retry attempt failed:
Traceback (most recent call last):
  File "/home/fquesada/anaconda3/envs/roya_fquesada/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 113, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/fquesada/anaconda3/envs/roya_fquesada/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 199, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/fquesada/anaconda3/envs/roya_fquesada/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/fquesada/anaconda3/envs/roya_fquesada/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/fquesada/anaconda3/envs/roya_fquesada/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/home/fquesada/anaconda3/envs/roya_fquesada/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql
2022-09-12 22:40:41,652 ERROR   SenderThread:92475 [internal_api.py:execute():202] 409 response executing GraphQL.
2022-09-12 22:40:41,653 ERROR   SenderThread:92475 [internal_api.py:execute():203] {"errors":[{"message":"run franceqa/roya/9 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2022-09-12 22:40:47,506 DEBUG   HandlerThread:92475 [handler.py:handle_request():138] handle_request: poll_exit
2022-09-12 22:40:51,353 ERROR   SenderThread:92475 [internal_api.py:execute():202] 409 response executing GraphQL.
2022-09-12 22:40:51,353 ERROR   SenderThread:92475 [internal_api.py:execute():203] {"errors":[{"message":"run franceqa/roya/9 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2022-09-12 22:40:52,607 DEBUG   HandlerThread:92475 [handler.py:handle_request():138] handle_request: poll_exit
2022-09-12 22:40:56,903 WARNING StreamThr :92475 [internal.py:is_dead():385] Internal process exiting, parent pid 92454 disappeared
2022-09-12 22:40:56,903 ERROR   StreamThr :92475 [internal.py:wandb_internal():147] Internal process shutdown.
2022-09-12 22:40:57,508 INFO    WriterThread:92475 [datastore.py:close():279] close: /home/fquesada/Documents/LiteFlowNet_roya/wandb/run-20220912_224031-9/run-9.wandb
2022-09-12 22:40:57,613 INFO    HandlerThread:92475 [handler.py:finish():807] shutting down handler
2022-09-12 22:40:57,908 INFO    MainThread:92475 [internal.py:handle_exit():78] Internal process exited
2022-09-12 22:40:57,909 WARNING MsgRouterThr:92475 [router.py:message_loop():74] EOFError seen in message_loop
